-- CREATE TABLE IF NOT EXISTS User (
--     id INT UNSIGNED AUTO_INCREMENT,
--     userId VARCHAR(20) NOT NULL,
--     name VARCHAR(100) NOT NULL,
--     password VARCHAR(255) NOT NULL,
--     email VARCHAR(100) NOT NULL,
--     PRIMARY KEY (id),
--     CHECK (CHAR_LENGTH(userId) BETWEEN 6 AND 20)
-- );

CREATE TABLE IF NOT EXISTS User (
    id INT UNSIGNED AUTO_INCREMENT,
    user_id VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL,
    PRIMARY KEY (id),
    CHECK (CHAR_LENGTH(user_id) BETWEEN 6 AND 20)
);
