CREATE TABLE IF NOT EXISTS User (
    id INT UNSIGNED AUTO_INCREMENT,
    userId VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL,
    PRIMARY KEY (id),
    CHECK (CHAR_LENGTH(userId) BETWEEN 6 AND 20)
);
